### ISSUE TITLE
Set up GPU access for model training and testing

### ISSUE THREAD

**Issue by KateCourt** [Organ-Quality-Assessment/project-management#1]
### Summary
We need a straightforward way to train and test models using the images stored in the cloud and the GPU time costed into the Oracle funding. Possibly create VM with the required dependencies already installed and bucket access setup, consider also providing Jupyter notebook instance. 

### What needs to be done?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by Fehings** [comment]
I will look into whether a job can be set up in a notebook and deployed to a GPU cluster, if we can do that it would be a nice user friendly way to do it!

**Comment by robinnandi** [comment]
Hassan is having issues using GPU in an Oracle notebook.

That issue is being tracked here: https://github.com/Organ-Quality-Assessment/Automated-Organ-Assessment/issues/42

Therefore I will close this one.
