### ISSUE TITLE
Add timed automated git pushes to the notebooks

### ISSUE THREAD

**Issue by Fehings** [Organ-Quality-Assessment/project-management#19]
### Summary
To ensure we have back ups of any oracle hosted code, and to avoid issues where multiple collaborators all think the other person will be handling version control, it would be beneficial to implement a cron job or similar to automate a weekly git commit and push to a dedicated 'unchecked' branch. 
This would probably be best done late on a Friday so it can capture the weeks work, and be at a time when it is unlikely to interrupt anyone actively working on the code. 

### What needs to be done?

- [ ] add a dedicated branch for handling these unchecked pushes
- [ ] Ensure we have cron or equivalent installed and available on the notebooks
- [ ] Implement a timed git commit and push
- [ ] replicate this for the newcaslte/ bradford notebooks
- [ ] test this is working before closing this issue.

**Comment by robinnandi** [comment]
I think this is best handled by requiring developers to be individually responsible for using git for version control. 

If it is not in the git repository, it has not been officially done yet. 

One notebook session per developer should ensure that files not yet pushed to the github repo don't get accidentally lost or overwritten by someone else.

**Comment by robinnandi** [comment]
We have moved to one notebook session per developer, which resolves this issue.
