### ISSUE TITLE
Provide Bradford access to images

### ISSUE THREAD

**Issue by KateCourt** [Organ-Quality-Assessment/project-management#2]
### What needs to be done?

- [ ] Ensure original images are stored in bucket that has very limited write access users
- [ ] Provide working copy for Bradford and others

**Comment by Fehings** [comment]
Set up VM & notebook with scripts to let them load in images from buckets (preauth? or find the commands to do that) so they can just hit the ground running with training on images.

**Comment by Fehings** [comment]
NB: could create them a new bucket so they can move data in and process as they like - keep the orig bucket locked down, read only access?

**Comment by Fehings** [comment]
Need to create users with correct authentication - members of data science group, have full access to one bucket, read access to raw bucket, permissions to deploy models and full control over model artefacts. Possibly need to also give serverless function access depending on how we end up deploying.

**Comment by robinnandi** [comment]
What about a simple web app with a view into the db?

e.g. can view list of images with their scores

**Comment by KateCourt** [comment]
Superseded
