### ISSUE TITLE
Review documentation of V1 Liver model 

### ISSUE THREAD

**Issue by robinnandi** [Organ-Quality-Assessment/project-management#23]
### Summary

The model documenation can be found here:

[https://unibradfordac-my.sharepoint.com/:f:/r/personal/hugail_bradford_ac_uk/Documents/ORQA%20-%20Bradford%20Team/liver%20documentation%20V1?csf=1&web=1&e=fuKXW2](url)

### What needs to be done?

Review the documentation making comments and corrections by adding "comments" to the document - so that we can work collaboratively with developers and other reviewers. 

Consider the following elements in your review (and any others you think are important):

- Clarity
- Does it give confidence that the model is robust? What could be added to give that confidence?
- Are there sufficient details to give an outsider a good overview of the what the model is and how it was built?
- Is the document written professionally with good spelling, grammar and punctuation?

**Comment by BryanLister** [comment]
Documentation of L1 Liver Model now reviewed.

**Comment by robinnandi** [comment]
I have reviewed the documentation for V1 of the Liver model and put my comments in the document on Bradford SharePoint.

One thing I missed out and should have done as part of the review is to reproduce the training results using the code/ notebook in the repo.

I will do this next and post my experience in this issue.
